### ISSUE TITLE
Update dev branch dependencies

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/starterkit-twig-demo#8]
The dev branch should rely on `dev-dev` of `core`. This is busting the install of the development edition of Twig (non-Drupal). I'll leave this to the @pattern-lab/drupal team to update since it looks like there are other changes going on here.

**Comment by EvanLovely** [comment]
I'll take care of this ASAP. Updating all Drupal PL repos to 2.0.0 is my top priority of the morning and should be done in the next 4 hours.

**Comment by EvanLovely** [comment]
All done! I've also updated the deps on `master` to use `^2.0.0`.
